### ISSUE TITLE
Ticker doesn't display on screen

### ISSUE THREAD

**Issue by hapklaar** [taoteh1221/Slideshow_Crypto_Ticker#10]
I'm testing out your ticker application on my Pi3 with HyperPixel LCD screen. Used your complete installation command and successfully installed everything.

However after rebooting the ticker doesn't show. The screen shows the Linux cli, like before. When I start the ticker manually, it shows:

```
admin@HapPiHyper:~ $ bash ~/dfd-crypto-ticker/bash/ticker-init.bash 
/usr/bin/xset:  unable to open display ":0"
/usr/bin/xset:  unable to open display ":0"
/usr/bin/xset:  unable to open display ":0"
/usr/bin/unclutter: could not open display
/home/admin/dfd-crypto-ticker/bash/cron/kucoin-auth.bash: line 12: /usr/bin/mkdir: No such file or directory
/home/admin/dfd-crypto-ticker/bash/cron/kucoin-auth.bash: line 13: /usr/bin/mkdir: No such file or directory
/home/admin/dfd-crypto-ticker/bash/cron/kucoin-auth.bash: line 18: /usr/bin/date: No such file or directory
/home/admin/dfd-crypto-ticker/bash/cron/kucoin-auth.bash: line 44: /home/admin/dfd-crypto-ticker/cache/json/kucoin-auth.json: No such file or directory
jq: error: Could not open file /home/admin/dfd-crypto-ticker/cache/json/kucoin-auth.json: No such file or directory
jq: error: Could not open file /home/admin/dfd-crypto-ticker/cache/json/kucoin-auth.json: No such file or directory
/home/admin/dfd-crypto-ticker/bash/cron/kucoin-auth.bash: line 64: /home/admin/dfd-crypto-ticker/cache/js/kucoin-auth.js: No such file or directory
BlueALSA detected - Disabling audio sandbox

(chromium-browser-v7:771): Gtk-WARNING **: 22:41:48.632: cannot open display: :0
admin@HapPiHyper:~ $ 

```

Using it with a HyperPixel TFT screen, which works ok. Can also run startx to view the desktop.

Do you know why it's failing?

**Comment by taoteh1221** [comment]
Hello. Make sure you are running the normal Raspberry Pi OS Desktop at startup. It cannot run starting as cli.

**Comment by taoteh1221** [comment]
Try using raspi-config to enable the desktop interface on startup. The ticker needs this, as it uses the chromium web browser only after the desktop interface loads.

**Comment by taoteh1221** [comment]
Also, you need to run Raspberry Pi OS Desktop. Looking at your error log it seems you system doesn't have /usr/bin/mkdir or /usr/bin/date on it?

**Comment by taoteh1221** [comment]
Not sure if this applies to your issue, but I revised some of the bash scripts in the new release today (download here at this link, or run the usual auto-install command as the desktop user running at startup): https://github.com/taoteh1221/Slideshow_Crypto_Ticker/releases

Just remember you need to login to the GRAPHICAL desktop interface to run the app, and hopefully you should be all set. Feel free to let me know if you have anymore questions / issues?

Thanks very much for your feedback, it helps alot to improve the user experience of this app.

**Comment by hapklaar** [comment]
Hi @taoteh1221 , thanks for your replies. I'll try to test your suggestions this weekend when I have some more time!

**Comment by taoteh1221** [comment]
Ok, good luck...holler if you get stuck.

**Comment by hapklaar** [comment]
I used raspi-config to start the desktop environment at boot and seem to make some progress now. After starting the desktop env I see my desktop on the screen. Then a few seconds after that the screen turns grey, then goes black. I guess chromium is started here. Then nothing happens anymore and the screen stays black. When I connect a mouse, I still see the moving mouse pointer on screen.

**Comment by taoteh1221** [comment]
Thanks for the great feedback. I did a major overhaul yesterday, and released a bug fix version. Could you please login to a terminal screen, and copy / paste / run this command (it will automatically upgrade you to the latest version of the ticker):

`
wget -O TICKER-INSTALL.bash https://git.io/Jqzjk;chmod +x TICKER-INSTALL.bash;sudo ./TICKER-INSTALL.bash
`

Let me know if that fixes the problem or not? Thanks! :)

**Comment by hapklaar** [comment]
Oh sorry, forgot to mention that I did update to the last version before I tried. The vid is from the pi with that new version.

So I guess that didn't fix my issue unfortunately.

**Comment by taoteh1221** [comment]
Also, make sure you install the app AS THE SAME USER RUNNING THE DESKTOP at startup.

**Comment by taoteh1221** [comment]
Crap, did you run the install script as the same user running the desktop? Interesting, we'll figure it out.

**Comment by taoteh1221** [comment]
Are you running Ubuntu on the device, or are you running Raspberry Pi OS?

**Comment by taoteh1221** [comment]
If you opposite-click on the blank browser window, and choose 'inspect', then switch to the 'console' tab, what do you see? Any error messages or notices?

**Comment by taoteh1221** [comment]
I do know that a brand new / fresh install of Raspberry Pi OS Desktop works for me, and another user who had issues. One other thing it may be is you need to reload the webpage...tap anywhere in the middle of the web page, then hit the F5 key on your keyboard. That should reload the ticker app in chrome.

**Comment by hapklaar** [comment]
Glad to hear you're interested :) To answer your questions:

- I ran the install script as the user logged into the desktop
- The Pi is running Raspbian (Raspbian GNU/Linux 10 (buster))
- I don't know what you mean by opposite-click , but no mouse button seems to do anything. Not getting an option to inspect. It seems I cant leave browser full screen at all. Am however able to summon up the start menu with the windows key and Chrome help with F1.
- F5 does nothing on the black screen.

Interesting detail might be that after I open Chromium help with F1, I cannot switch back with alt tab, meaning there is no other Chromium window present I guess? Might be that the browser never started.

**Comment by taoteh1221** [comment]
Interesting, thanks for the feedback.

I took a close look at the install script today, and found a few bugs which I patched and uploaded to github. If you wouldn't mind running this slightly-modified version of the auto-install script command, that would be great:

`
wget --no-cache -O TICKER-INSTALL.bash https://git.io/Jqzjk;chmod +x TICKER-INSTALL.bash;sudo ./TICKER-INSTALL.bash
`

Notice it says --no-cache, which will force downloading my patched version of the installation script. Please let me know if it fixes your issues or not?

**Comment by taoteh1221** [comment]
I'll be releasing another bug fix sunday evening my time, if you want to wait until then I'll let you know when it's ready (it fixes font / positioning config settings, so they work properly).

**Comment by hapklaar** [comment]
Seems like you fixed it! Ticker showed on startup, albeit upside down, but that was easily fixed by changing config.js

![20210321_134847](https://user-images.githubusercontent.com/7703320/111905499-44b82b00-8a4c-11eb-93c1-a5408717c4e2.jpg)

first impressions and some ideas:

- Looks great on my HyperPixel (800x480) screen. Might look into increasing font sizes, as the ticker is now only using a smal part of the screen. Maybe this can be auto adjusted based on the resolution detected, or in the setup script?
- Maybe add a little graph to show the 24h or 1h trend, to make use of extra screen real estate. I understand this would be a major change :)
- Would it be possible to configure the delay between slides, or even the method of sliding?
- Are you planning on including the Bitfinex exchange?

**Comment by taoteh1221** [comment]
Hello, glad to see you got it running! :)

I just did a bug fix release (v3.02.3) a few minutes ago, which addresses alot of your points: 

https://github.com/taoteh1221/Slideshow_Crypto_Ticker/releases

Changelog:
- Bug fix for font sizes / positioning not updating from config values
- Bug fixes for auto-install script
- Bug fixes for runtime bash scripts

In the new bug fix release, you should now be able to adjust the font sizes and vertical / horizontal position to take up the entire screen and center it, sorry about that.

The arrow size should automatically adjust when you change the ticker price size, the arrow size is just the RATIO to ticker size (I worded the notes next to the configs better for clarity in the new release). 

Run this command in the terminal, to upgrade to the new bug fix release I put out earlier today:

`
wget --no-cache -O TICKER-INSTALL.bash https://git.io/Jqzjk;chmod +x TICKER-INSTALL.bash;sudo ./TICKER-INSTALL.bash
`

I had gotten a request from somebody else on showing the 24 hr trend. I've thought through how to do the backend programming, BUT haven't thought of a spot it would fit on the screen yet, that doesn't make things "too busy" / confusing yet. Any ideas? Generally, we adjust the font sizes and vertical / horizontal position to take up the entire screen and center it.

I will add Bitfinex API support in the next release, an let you know.

You can already set the delay between slides here in config.js: 

https://github.com/taoteh1221/Slideshow_Crypto_Ticker/blob/main/config.js#L98

I will have to look into changing the method of sliding (effect). What did you have in mind for a different transition effect? 

Thanks for all the great feedback, I appreciate it! :)

**Comment by taoteh1221** [comment]
A little tip to make adjusting the font sizes / screen positioning easier for you: Everytime after you edit / save config.js, you can reload the chrome ticker page with this command in the terminal, to see your changes:

`
~/reload
`

**Comment by hapklaar** [comment]
Wonderful! Setting font sizes now works correctly 👍 Increased the font sizes quite a bit and it now looks the part on my screen. Currently I have a static display of BTCUSD price on Coinbase, by just having that single Exchange in config.js

![image](https://user-images.githubusercontent.com/7703320/111920247-31c64a80-8a8e-11eb-8faa-82d030185640.png)

With the delay between slides I meant the amount of time the screen goes black between slides (the fade out/fade in period). Can that be configured/shortened? Was just a tad slow for me.

For transition effects I was thinking maybe something like slide in from bottom or right for example.

About the 24hr trend. This could fit on the bottom half of the screen, as long as the font size isn't too big. A small rectangular line graph might be doable. Might be good to make this configurable for those who find this will clutter their screen too much indeed.

**Comment by taoteh1221** [comment]
Looks good, sweet! :)

Ah, yes I can make the transition time between tickers a configuration setting pretty easily...will add that in the next release.

I'll look into adding the option to show a 1hr / 1day / 1week / 1month trend stat somewhere (configurable in config.js), as well as different transition effects when switching tickers. Might take awhile to find enough time for those two features to be added fully and tested.

Thanks for the feedback, enjoy the ticker. I'll post back here when any of these features are added to a new release.

**Comment by hapklaar** [comment]
Sure thing, Thanks for all the effort! 🥇

**Comment by taoteh1221** [comment]
No problem, I really appreciate the feedback. It helps make the app kick @$$. Thanks for taking the time to do that.

**Comment by hapklaar** [comment]
Hi @taoteh1221 one more question. How does the 24hr volume get calculated? I have had the BTC-USD Coinbase ticker on my screen for the last couple of days and havent seen the volume drop to 0. It just seems to go up (and a little bit down) all the time which seems strange to me :)

**Comment by taoteh1221** [comment]
The volume is provided by the exchange API (otherwise the app doesnt show any volume). I think it's a rolling 'window', always the volume over the last 24 hour 'window'. I have no idea how exchanges calculate it though, just a guess.

**Comment by taoteh1221** [comment]
Transition speed config and Bitfinex support is in the latest crypto ticker release: https://github.com/taoteh1221/Slideshow_Crypto_Ticker/releases
