### ISSUE TITLE
loading with kucoin

### ISSUE THREAD

**Issue by Greensize** [taoteh1221/Slideshow_Crypto_Ticker#11]
I have had a bug for 1 hour with kucoin, the other exchanges are working fine
<img width="775" alt="Capture d’écran 2021-03-19 à 20 58 22" src="https://user-images.githubusercontent.com/80355995/111836062-0d376a80-88f6-11eb-871f-563b4a3f3e39.png">

**Comment by taoteh1221** [comment]
There is a new bug fix release available for download, which fixes many things, including kucoin markets: https://github.com/taoteh1221/Slideshow_Crypto_Ticker/releases

To quickly / easily install this upgrade, copy / paste / run the command below in a terminal program (using the 'Terminal' app in the system menu, or over remote SSH), while logged in AS THE USER THAT WILL RUN THE APP (user must have sudo privileges):

`
wget -O TICKER-INSTALL.bash https://git.io/Jqzjk;chmod +x TICKER-INSTALL.bash;sudo ./TICKER-INSTALL.bash
`


Follow the prompts, and the automated script will install / configure the ticker. KUCOIN MARKETS #WILL NOT WORK# IF YOU DO NOT INSTALL THE TICKER PROPERLY!

**Comment by taoteh1221** [comment]
Restart your machine after upgrading too. If you have the same chromuim caching issue you had before, click in the middle of the ticker window, and then hit the F5 key on your keyboard. This should reload the ticker, and run the upgraded version.

**Comment by taoteh1221** [comment]
I spent a lot of time fixing everything for kucoin in the the bug fix release yesterday, I hope it's workig ok for you now? It should even auto-fix if it detects that 'loading...' issue again. Every 5 minutes it tries to auto-fix any kucoin issues, adjustable config setting for the time period is here: https://github.com/taoteh1221/Slideshow_Crypto_Ticker/blob/main/config.js#L105

**Comment by Greensize** [comment]
I reinstalled just now. everything is working fine :) Thank you

**Comment by Greensize** [comment]
Good Job!

**Comment by taoteh1221** [comment]
Cool, your welcome! :) I think you should be all set now, but just holler if it acts up again. Kucoin's API is a lot stricter than most exchange websocket APIs...had to jump though a lot of hoops to get it running smoothly. :o

**Comment by taoteh1221** [comment]
I will be releasing another bug fix sunday evening my time, that fixes changing the font sizes and ticker position on the screen. If either of those are issues for you just run the auto-install script, and it will automatically upgrade you once I release the new version on github.

**Comment by taoteh1221** [comment]
New release is out for the crypto ticker app, that fixes letting you change the text size / position on the screen:

https://github.com/taoteh1221/Slideshow_Crypto_Ticker/releases

To quickly / easily upgrade to this release, copy / paste / run this command in the 'Terminal' app from your system menu:

`
wget --no-cache -O TICKER-INSTALL.bash https://git.io/Jqzjk;chmod +x TICKER-INSTALL.bash;sudo ./TICKER-INSTALL.bash
`

Any custom markets you added will be backed up in the /home/pi/dfd-crypto-ticker/ folder, in a new backup file named "config.js.BACKUP.DATE_HERE". You can just copy / paste them from the backup into the new / upgraded config.js file.

Thanks for your feedback, it makes this app better for everyone! :)

**Comment by taoteh1221** [comment]
A little tip to make adjusting the font sizes / screen positioning easier for you: 

Everytime after you edit / save config.js, you can reload the chrome ticker page with this command, if you copy / paste / run it in the 'Terminal' app in your system menu, to see your changes:

`
~/reload
`

**Comment by taoteh1221** [comment]
Restart your Pi after upgrading too, so it loads the upgrade. Enjoy, and thanks again for the donation you made through paypal! :)
