### ISSUE TITLE
Request: coinmarketcap

### ISSUE THREAD

**Issue by rschneider1509** [taoteh1221/Slideshow_Crypto_Ticker#15]
Is this hard to implement?
Or some other Exchange that lists safemoon :D 

Ty for creating this, works fine on my old dusty rpi2!

**Comment by taoteh1221** [comment]
Thanks for the feedback, that's great it works on an old RP2! CMC doesn't have a websockets API, which is what the ticker uses. BUT Binance's DEX does: https://docs.binance.org/api-reference/dex-api/ws-streams.html

Is safemoon on Binance DEX I wonder?

**Comment by rschneider1509** [comment]
Ty for ur reply.
I found, cmc got some kind of api, that's why I asked :)
This guy uses it for his tracker:
https://github.com/Zaldr0n/SafemoonIndicator

Safemoon is very new and seems only listed on bitmart and whitebit yet :p

**Comment by taoteh1221** [comment]
Unfortunately like I said, CMC does not have a 'websockets' API (they have a 'rest' API). This ticker requires a 'websocket' API to connect to. 

Looks like safemoon is on Binance's Pancakeswap DEX here too: https://www.coingecko.com/en/coins/safemoon#markets

**Comment by rschneider1509** [comment]
Thx, i will find my way through this :)

taoteh1221 ***@***.***> schrieb am Mi., 7. Apr. 2021, 17:03:

**Comment by taoteh1221** [comment]
If it's on the Binance MAIN exchange yes, but I do not have Binance DEX added yet (it may be in the next release later this month). I'll let you know if PancakeSwap is supported with their DEX websocket API, as I believe safemoon is on there.

**Comment by rschneider1509** [comment]
u can close this. Bitmart lists SAFEMOON :)

**Comment by taoteh1221** [comment]
Cool. Ok, closing.
