### ISSUE TITLE
Request: Allow changing font-weight + changing transition speed between slides

### ISSUE THREAD

**Issue by BerkeAras** [taoteh1221/Slideshow_Crypto_Ticker#16]

**Comment by taoteh1221** [comment]
Good ideas, thanks for the feedback. The slide transition speed has already been slated to be added in the next release: https://github.com/taoteh1221/Slideshow_Crypto_Ticker/issues/10#issuecomment-803573680

**Comment by BerkeAras** [comment]
Btw: how can I end the ticker from terminal? @taoteh1221

**Comment by taoteh1221** [comment]
@BerkeAras This should do the trick:

`pkill -o chromium`

**Comment by taoteh1221** [comment]
Latest version has better start / stop / restart support: https://github.com/taoteh1221/Slideshow_Crypto_Ticker/releases

**Comment by taoteh1221** [comment]
And transition speed config now exists: https://github.com/taoteh1221/Slideshow_Crypto_Ticker/blob/main/config.js#L70
