### ISSUE TITLE
How to disable auto start?

### ISSUE THREAD

**Issue by cambobulate** [taoteh1221/Slideshow_Crypto_Ticker#21]
I've been looking into rclocal and init files, but I don't really know what I am looking for.

Is there a command to disable auto startup?

Maybe to enable auto start in the future?

Thank you for your help.

**Comment by cambobulate** [comment]
Figured out which service to disable and how. Thanks

**Comment by taoteh1221** [comment]
Just skip the 'automatically configure' part of the auto-install routine. That's the part that makes it auto-start, AND keeps the screensaver off.

**Comment by cambobulate** [comment]
I meant after having already installed it. I ended up just disabling the service. Thanks

**Comment by taoteh1221** [comment]
Glad you figured it out, thanks for the feedback.
