### ISSUE TITLE
Switch from Gdax API to Coinbase Pro API

### ISSUE THREAD

**Issue by cniweb** [taoteh1221/Slideshow_Crypto_Ticker#23]
The Gdax Websocket Feed API for Coin base is offline:
https://ws-feed.gdax.com
Error 526 (Invalid SSL certificate)

Line of code:
https://github.com/taoteh1221/Slideshow_Crypto_Ticker/blob/55376040dca8fe88ae05dca7ca3a77569b06c398/js/functions.js#L643

The gdax package is deprecated and might have to be removed from NPM.
Please migrate to the coinbase-pro package to ensure future compatibility.

The official Node.js library for Coinbase's Pro API:
https://docs.pro.coinbase.com/

**Comment by cniweb** [comment]
Websocket Feed URL:
wss://ws-feed-public.sandbox.pro.coinbase.com

**Comment by taoteh1221** [comment]
Hello. Thanks for the head's up! Looks like the official documentation have it as this now: wss://ws-feed.pro.coinbase.com

That works fine for me?

**Comment by taoteh1221** [comment]
I don't think we want the sandbox endpoint, as that is usually just for testing I believe.
