### ISSUE TITLE
Was working yesterday. Now displays (ERROR) and loading

### ISSUE THREAD

**Issue by JVTEAM** [taoteh1221/Slideshow_Crypto_Ticker#25]
I had it running for a week now. Now it no longer loads the markets and just displays ETH(Error) Loading... or BTC (Error) Loading...

**Comment by JVTEAM** [comment]
Changing wss to wss://ws-feed.pro.coinbase.com fixed it.

**Comment by taoteh1221** [comment]
Thanks for reporting, this will be fixed in the upcoming v3.03.0 release: https://github.com/taoteh1221/Slideshow_Crypto_Ticker/pull/24
