### ISSUE TITLE
Bitcoin Ticker not connecting now

### ISSUE THREAD

**Issue by buttwhisker** [taoteh1221/Slideshow_Crypto_Ticker#29]
Hi,
I successfully built the bitcoin ticker and it was working fine for weeks, and now it just wont connect to any live feed. It just says BTC  (Error) in red. Its connected the internet so its not that. My son has one as well at his house, and his has also stopped working at the same time mine did.

Can you help us please?

**Comment by taoteh1221** [comment]
Hello. Can you confirm both your raspberry pis have internet connections? There was an upgrade the other week for coinbase markets no longer working (had to update to their newest API address): https://github.com/taoteh1221/Slideshow_Crypto_Ticker/releases

**Comment by buttwhisker** [comment]
Hi, yes both have internet connection. How do I install this upgrade please? 
I am new to this stuff. Any advise you can give would be very much appreciated.

**Comment by taoteh1221** [comment]
Sure, no problem. How did you install initially, manually or with the auto-install script? See the sections "AUTOMATIC INSTALLATION" and "MANUAL INSTALLATION (IF AUTO-INSTALL SCRIPT FAILS, ETC)" in this README file for full instructions: 

https://raw.githubusercontent.com/taoteh1221/Slideshow_Crypto_Ticker/main/README.txt

Let me know if you get stuck doing any of it?

**Comment by buttwhisker** [comment]
Hi, 
perfect! All done and now working. 
thank you so much :-) 👍 
Now I can see just how much I am losing... lol

**Comment by taoteh1221** [comment]
Your welcome! :) Sweet, except for the losing part. lol Glad it's working again for you.
