### ISSUE TITLE
CryptoTicker Screen

### ISSUE THREAD

**Issue by spenadel** [taoteh1221/Slideshow_Crypto_Ticker#34]
Hi - I love the program.  I'm having a problem with my unit using the same screen that you recommended.  The window for the crypto ticker is not centered in the screen, showing the desktop around the right/bottom edges.  I'm not sure how to remedy this
![IMG_0119](https://user-images.githubusercontent.com/18075704/141647976-feb17a2c-a935-4af6-8777-235efcb78612.jpg)
.

**Comment by spenadel** [comment]
I think I figured it out.  I changed the screen resolution.

**Comment by taoteh1221** [comment]
@spenadel Thanks for the user feedback. Try adjusting the screen positioning / font sizes in config.js (the ticker app configuration file). See here at this link, for an example of what I'm talking about: https://github.com/taoteh1221/Slideshow_Crypto_Ticker/blob/main/config.js#L70

**Comment by taoteh1221** [comment]
Run the command ~/ticker-restart to apply any changes you make (in the 'terminal' app in the raspi app menu, or over remote SSH terminal login).

**Comment by taoteh1221** [comment]
Glad you like the app, thanks again for the feedback! :) Just holler if you get stuck on anything else, or have anymore questions. Enjoy the ticker! :)
