### ISSUE TITLE
KDA-USDT error

### ISSUE THREAD

**Issue by garyrizzo1992** [taoteh1221/Slideshow_Crypto_Ticker#36]
Hardware: Raspberry pi 4 8 GB.

Pair: exchange_markets['kucoin'] = 'KDA-USDT';

Description: After some time running fine, it suddenly started throwing an error. ( https://ibb.co/wgsS70t )
Are there some logs i can take a look at for a more detailed error?

**Comment by taoteh1221** [comment]
Thanks for the report @garyrizzo1992. No logs, as this is mostly a client-side JavaScript based ticker running by file in chromium (not web server). That said, Kucoin does require the ticker to use some shell scripting in the background, but I have not added logging to that yet. I suspect the Kucoin config isn't getting refreshed properly (as it requires). Thanks very much for the report, I'll add logging / debugging to this sometime next week (too busy this week already).

**Comment by taoteh1221** [comment]
Closing this, as the kucoin API looks fixed with the latest patch (v3.05.1 coming out by monday 12pm EST, still testing now to be sure): https://github.com/taoteh1221/Slideshow_Crypto_Ticker/commit/eb20a2e03b7ddb57c509a38d43164d42be576e5a
