### ISSUE TITLE
hide "(Exchange)" after the Coin name

### ISSUE THREAD

**Issue by rschneider1509** [taoteh1221/Slideshow_Crypto_Ticker#37]
Is it Possible to hide/disable the View of the used exchange?

**Comment by taoteh1221** [comment]
No, hiding exchange is currently not an option. Let me think it over, to make sure it wouldn't be more confusing than useful for most users. Thanks very much for the feedback. It might be ok to add it as a setting to disable showing it.

**Comment by rschneider1509** [comment]
i tried messing arround in the functions.js in the "// Open socket" section.
But i "solved" my problem by just lowering the Title Size.
(Problem was, the title was too long and the price was centered to the title, so even the price was not readable without scrolling :D)

So i dont realy have a Problem anymore, but i would like it better if i could turn it of like u mentioned :)
thanks for your reply. nice project. Coworkers like it :)

**Comment by taoteh1221** [comment]
Cool, glad you found a workaround. I will add the ability to remove the exchange name as a setting in the next release. I'll ping you here when it's available. Thanks for the compliments and feedback, glad to hear people like it! :)

**Comment by taoteh1221** [comment]
Added 'show_exchange_name' setting in config.js, to hide / show exchange name in the ticker: https://github.com/taoteh1221/Slideshow_Crypto_Ticker/commit/37f25fec6f4ee783c52d3857a122c591021859e0
