### ISSUE TITLE
No Decimal Places After Certain Coin 

### ISSUE THREAD

**Issue by spenadel** [taoteh1221/Slideshow_Crypto_Ticker#38]
Some coin, such as BTC, ETH, SOL (using Coinbase as the exchange) only reflect whole USD amounts, with no decimal places.  Is this a function of the exchange or am I not setting a parameter properly?

**Comment by taoteh1221** [comment]
Any coin worth 100 or more rounds to no decimals. Any coin worth between 1 and 99.99 displays 2 decimals. Any coin under 1 displays 5 decimals.

**Comment by spenadel** [comment]
Thank you!

**Comment by taoteh1221** [comment]
No problem. :) I can make an advanced settings section where you could adjust this. Would be pretty easy, I'll do it for the next release.

**Comment by taoteh1221** [comment]
New version (v3.06.0 coming out this weekend) lets you set the decimal MINIMUM, default is 0 (disabled): https://github.com/taoteh1221/Slideshow_Crypto_Ticker/commit/833eb5adc6561891f1db18785113c58747f0c6e9
