### ISSUE TITLE
Tracker freezes on first screen, eventually crashes

### ISSUE THREAD

**Issue by Draco-Red** [taoteh1221/Slideshow_Crypto_Ticker#39]
I'm trying to set this up on a Pi Zero W running raspbian-stretch.  So far the install seems to go well, and after reboot it loads the first screen showing ETH-USD on Coinbase, however it never seems to move past that and eventually freezes entirely crashing Chromium.  

I'm wondering if the Pi Zero just isn't fast enough or have enough RAM to run this properly, or if there's some optimizations that I can do to get it working correctly.  

Thanks.

**Comment by taoteh1221** [comment]
Thanks for the feedback @Draco-Red. Have you tried doing just one ticker instead of multiple tickers, to make sure you're not overloading the raspi zero w? That's a very slow machine, I have one. Never added an lcd to mine though, I just run it headless as a server

**Comment by taoteh1221** [comment]
Closing for now, unless you have more information to help troubleshoot this.
