### ISSUE TITLE
Please add Coingecko

### ISSUE THREAD

**Issue by tistheszn** [taoteh1221/Slideshow_Crypto_Ticker#40]
Would be a perfect app if it included coingecko!

**Comment by taoteh1221** [comment]
Thanks for the feedback @tistheszn. Coingecko doesn't have a websocket API unfortunately. This app uses websocket APIs to get the 'live stream' / 'real time' data. I may try to emulate websocket effects for coingecko data some day, we see how it goes.

**Comment by tistheszn** [comment]
great, thank you for the quick response! Really enjoy the app otherwise.

**Comment by taoteh1221** [comment]
Cool, no problem. I appreciate feedback very much.

**Comment by dongodao** [comment]
![ticker](https://user-images.githubusercontent.com/15836737/145332988-bca2c14f-48c5-4f94-9055-0ae551b95c75.jpg)
Can't wait until you implement Coingecko. I really like your project. Thank you.

**Comment by taoteh1221** [comment]
Thanks for the compliments @dongodao ! :) Nice layout design work, will have to keep that in mind when I add trends as an optional 3rd / 4th row. 👍

**Comment by taoteh1221** [comment]
Coingecko support has been added for the upcoming v3.06.0 release, due out Christmas day (late in the evening USA Eastern time, after some final testing confirmations): https://github.com/taoteh1221/Slideshow_Crypto_Ticker/commit/848ad2508a3cd5289db0f56e4d04f9b0ab92b9a6
