### ISSUE TITLE
How to use Kraken or crypto.com?

### ISSUE THREAD

**Issue by mrsouleater5000** [taoteh1221/Slideshow_Crypto_Ticker#55]
Hello together,

I have a question though, about adding Kraken as an Exchange. It always shows me only Loading... despite correct configuration. And is there a possibility to add crypto.com too ?

Best regards mrsouleater

![IMG_20230620_161113](https://github.com/taoteh1221/Slideshow_Crypto_Ticker/assets/137195111/0fbb396c-7d24-41fd-95d4-3d1abf4b731c)

**Comment by taoteh1221** [comment]
Hello @mrsouleater5000.

On crypto.com support, it's already on the TODO list here (not sure when I'll make time to do this yet):

https://github.com/taoteh1221/Slideshow_Crypto_Ticker/blob/main/DOCUMENTATION-ETC/TODO.txt#L47

On your kraken markets configuration issue, I'll need to see your kraken config in config.js, so I can determine the problem. If you could copy / paste your config here, that would work.

**Comment by taoteh1221** [comment]
Basically, make sure it looks like this:

https://github.com/taoteh1221/Slideshow_Crypto_Ticker/blob/main/config.js#L27

AND make sure you always properly include the exchange market config in quotes like this example does.

**Comment by mrsouleater5000** [comment]
Here is the full code.

Thanks for your help!

// Copyright 2019-2021 GPLv3, Slideshow Crypto Ticker by Mike Kilday: http://DragonFrugal.com

var exchange_markets = []; // LEAVE ALONE, AND DON'T DELETE (REQUIRED!)


//  TYPOS LIKE MISSED SEMICOLONS / MISSED QUOTES / ETC WILL BREAK THE APP, BE CAREFUL EDITING THIS CONFIG FILE!


// ############## PER-EXCHANGE FORMATTING EXAMPLES ##########################
////
// Which crypto asset(s) to display on the ticker
// Separate with pipe | symbol to "slideshow" between multiple tickers on the same exchange
////
// Kraken formatting example: 'XBT/USD|XBT/CAD|XBT/EUR|ETH/USD|ETH/EUR|ETH/CAD|'
// Coinbase formatting example: 'BTC-USD|BTC-GBP|ETH-USD|ETH-BTC|ETH-EUR|MKR-USD|MKR-BTC|MANA-USDC'
// Binance formatting example: 'btcusdt|ethusdt|ethbtc|mkrusdt btcusd'
////
////
// Binance markets (set to '' to disable)
exchange_markets['binance'] = 'btceur';
////
////
// Coinbase markets (set to '' to disable)
//exchange_markets['coinbase'] = 'BTC-USD|BTC-EUR';
////
////
// Kraken markets (set to '' to disable)
//exchange_markets['kraken'] = 'BTC/EUR|BTC/USD|';
////
////
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// I M P O R T A N T   S E T U P   I N F O R M A T I O N !!!!!!!!!!!!!!!!!!!!
// Run COMMAND "~/ticker-restart" (WITHOUT QUOTES) TO SHOW UPDATED SETUP!!!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


// Screen orientation (offset in degrees)
var orient_screen = 180; // Normal = 0, Flipped = 180, Sideways = 90 or 270


// Vertical position (adjusts the ticker's vertical position up/down)
// CAN BE NEGATIVE, TO GO THE OPPOSITE WAY
var vertical_position = 36; // Default = 36


// Horizontal position (adjusts the ticker's horizontal position left/right)
// CAN BE NEGATIVE, TO GO THE OPPOSITE WAY
var horizontal_position = 10; // Default = 10


// Slideshow transition speed IN SECONDS (can be decimals)
var transition_speed = 0.75; // Default = 100.0


// ALL font weights (for ALL ticker text)
var font_weight = 'normal'; // Default = 'normal', can be any proper CSS font weight value

// Title font size
var title_size = 55; // Default = 55


// Ticker arrow size ratio (to ticker size), DECIMAL NUMBER FORMAT X.XX OF 1.00 OR LESS
// THIS #ALREADY AUTO-RESIZES# BASED ON THE TICKER SIZE, SO YOU USUALLY CAN LEAVE THIS
// #AS-IS#, UNLESS YOU WANT THE RATIO TO TICKER SIZE DIFFERENT!
var arrow_size = 0.65; // Default = 0.65


// Ticker font size
var ticker_size = 66; // Default = 66


// Maximum decimal places for values worth under 1.00 in unit value, for prettier / less-cluttered interface
var max_ticker_decimals = 7; // Default = 7


// 24 hour volume font size
var volume_size = 40; // Default = 40


// Hide volume section, IF NO VOLUME WAS PROVIDED
var hide_empty_volume = 'no'; // 'no' / 'yes'

// Text color (https://www.w3schools.com/colors/colors_picker.asp)
// '#colorcode'
var text_color = '#c6c6c6'; // Default = '#c6c6c6'


// Background color (https://www.w3schools.com/colors/colors_picker.asp)
// '#colorcode'
var background_color = '#000000'; // Default = '#000000'


// Use a google font...set as null for default system serif font
// Runs the ticker in ANY google font found at: https://fonts.google.com
// 'fontname' IN QUOTES for ANY google font, OR null to skip (null MUST BE LOWERCASE WITHOUT QUOTES)
var google_font = 'Varela Round'; // Default = 'Varela Round'


// Seconds between "slideshowing" multiple tickers (if multiple assets configured)
// SET TO 0 FOR AUTO MODE (trys to show all tickers in 1 minute, BUT has a 5 second per-ticker MINIMUM)
var slideshow_speed = 0; // Default = 0


// EMULATED / dynamic monospace font WIDTH spacing (percent of EACH font size as a decimal)
// (ALL font widths for ticker/volume numbers are emulated as monospace, so numbers don't "jump around" when changing in real-time)
// DECIMAL NUMBER FORMAT X.XX OF 1.00 OR LESS, OR null to skip (null MUST BE LOWERCASE WITHOUT QUOTES)
var monospace_width = 0.65; // Default = 0.65


// Minimum number of minutes to wait before auto-reloading the app IF ERRORS ARE DETECTED THAT MAY BE FIXED WITH A RELOAD
// (#NOT# USED FOR DROPPED API CONNECTIONS, SINCE WE AUTO-RECONNECT WITHOUT RELOADING EVERYTHING, but this is very helpful
// if the kucoin API token expires / any other javascript app cache variables need to be reloaded with new values)
var auto_error_fix_min = 5; // Default = 5



// All #ACTIVATED# market pairings (what the asset is paired with in markets), AND their currency symbols
// ADD ANY NEW SUPPORTED (CHECK WITH THE EXCHANGE) MARKET PAIRINGS HERE YOU WANT #ACTIVATED# IN THIS APP


// Fiat-equivelent market pairings (KEYS #MUST BE# UPPERCASE)
var fiat_pairings = {
                                                                'AUD': 'A$',
                                                                'BRL': 'R$',
                                                                'CAD': 'C$',
                                                                'CHF': 'CHf',
                                                                'EUR': '€',
                                                                'GBP': '£',
                                                                'HKD': 'HK$',
                                                                'JPY': 'J¥',
                                                                'RUB': '₽',
                                                                'SGD': 'S$',
                                                                'TUSD': 'Ⓢ ',
                                                                'USD': '$',
                                                                'USDC': 'USDC ',
                                                                'USDT': '₮ ',
                                                                };


// Crypto market pairings (KEYS #MUST BE# UPPERCASE)
var crypto_pairings = {
                                                                'BNB': 'Ⓑ ',
                                                                'BTC': 'Ƀ ',
                                                                'ETH': 'Ξ ',
                                                                'USDC': 'Ⓢ ',
                                                                };

**Comment by taoteh1221** [comment]
Thanks @mrsouleater5000, that helps a lot. Please see the screenshot image I have attached to this message. I highlighted where you need to delete errors to get it to work. If you do NOT want coinbase activated, just ignore that part. 

Let me know if it still gives you any issues after updating / restarting the ticker with these changes.

![Workspace 1_029](https://github.com/taoteh1221/Slideshow_Crypto_Ticker/assets/1760489/1f830607-6656-4c23-b6da-61685ca42815)

**Comment by mrsouleater5000** [comment]
Does not work for me. I have had it tested before. 

exchange_markets['kraken'] = 'BTC/EUR|BTC/USD';

**Comment by taoteh1221** [comment]
Ok, I'll try using your exact config this weekend, and see what's wrong. Are you running the latest version? You can re-run the auto-installer to reinstall. The biggest thing is to carefully edit config.js, by changing as little as possible.

**Comment by taoteh1221** [comment]
Yes, run that to upgrade. Sorry, haven't made time to test your malformed config.js yet, to see where the issue is.

**Comment by mrsouleater5000** [comment]
Nothing happens. after I executed the command All the same BTC (Kraken) Loading... The command was executed but nothing more.

**Comment by taoteh1221** [comment]
> Nothing happens. after I executed the command All the same BTC (Kraken) Loading... The command was executed but nothing more.

Sorry, I'm unable to replicate ANY of your problems. Unless you can give me these SPECIFICS BELOW, to try and replicate your issues, there is not much more I can do to help you (please be more specific other than "nothing happens"):

The CURRENT version of the crypto ticker you are running (located at top of file: /js/core/init.js).

The name / version of the operating system you are running on the machine running the ticker.

The SCREEN OUTPUT of the install command:
wget --no-cache -O TICKER-INSTALL.bash https://tinyurl.com/install-crypto-ticker;chmod +x TICKER-INSTALL.bash;sudo ./TICKER-INSTALL.bash

**Comment by taoteh1221** [comment]
Closing this since it's been 3 weeks with no response. Feel free to re-open this issue, if you have any specifics to report that can help me replicate this issue you had. Thanks for your feedback.
