### ISSUE TITLE
Pi Zero w support?

### ISSUE THREAD

**Issue by reddai75** [taoteh1221/Slideshow_Crypto_Ticker#65]
Hi! thanks for this project, will it work on a PI zero ?

**Comment by taoteh1221** [comment]
I have it running OK on a pi zero w v2. That said, I doubt it would easily run on a zero w v1 though. The included auto-install script TICKER-INSTALL.bash will ask you if you want to update the virtual memory swap space, which should help a lot on low memory devices like the zero.
