### ISSUE TITLE
Slideshow is too slow

### ISSUE THREAD

**Issue by LuxStatera** [taoteh1221/Slideshow_Crypto_Ticker#69]
In the config file I have adjusted the slideshow seconds a couple times but it is still slow. 
The default is .75
I have tried .5 and .05 and .005
My goal is to get it to change to a different crypto every 5 seconds but for some reason it takes minutes. Am I doing something wrong?

**Comment by taoteh1221** [comment]
So first off, only use whole numbers here:
https://github.com/taoteh1221/Slideshow_Crypto_Ticker/blob/main/config.js#L206

Using decimals is NOT supported.

**Comment by taoteh1221** [comment]
Sounds like you are adjusting the wrong thing, default is 9. Try reinstalling, and reading all directions next to each setting. "slideshow_speed" is the setting you want. It sounds like you possibly corrupted the config, changing something else...so it may be messed up now, unless you re-install first.

**Comment by LuxStatera** [comment]
I was messing with the wrong slideshow settings. My bad. Thank you for the help

**Comment by taoteh1221** [comment]
Sure, no problem.
