### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by Greensize** [taoteh1221/Slideshow_Crypto_Ticker#9]
There seems to be a problem with the missing kucoin-auth.js file?

**Comment by Greensize** [comment]
Sorry to annoy you...
I did the command and install / uninstall several times but I still have the black screen

**Comment by Greensize** [comment]
<img width="1141" alt="Capture d’écran 2021-03-16 à 19 53 32" src="https://user-images.githubusercontent.com/80355995/111374960-02829880-869e-11eb-973c-5004409f519d.png">

**Comment by taoteh1221** [comment]
No worries, I just needed to confirm that you tried the install script, so we can figure it out. Let me try to replicate your issue on a fresh raspberry pi install on my raspberry pi. Are you using ubuntu or raspberry pi os on your machine? I'll install whichever one your using.

**Comment by Greensize** [comment]
It’s a raspberry pi os

**Comment by taoteh1221** [comment]
Ok, thanks for the information. I'm going to do a fresh install of raspberry pi os on my device, and see if this happens for me too, so I know what to fix.

**Comment by taoteh1221** [comment]
Ok, I just did a fresh install of Raspberry Pi OS Desktop version. Everything installed fine for me using the auto-install script. Sorry, I'm not sure what your problem is, and I cannot fix it unless I encounter the same error as you. Everything seems to be working ok for me.

**Comment by taoteh1221** [comment]
If you still have issues, please run this command and copy / paste the output or send me a screenshot of the output:

`
bash ~/dfd-crypto-ticker/bash/ticker-init.bash
`

**Comment by taoteh1221** [comment]
I'm going to release a bug fix version tomorrow, that will at least load all markets except kucoin, if needed kucoin variables are not detected due to a botched installation routine.

**Comment by taoteh1221** [comment]
I fixed the blank screen issue for you, BUT you'll need to follow the instructions in the error log window you showed me to get kucoin to work (see the screenshot image I attached to this message). You'll see this same message in your browser after you upgrade. Follow the instructions, and kucoin will also show in the ticker.

Here is a link to download the fixed version: https://github.com/taoteh1221/Slideshow_Crypto_Ticker/releases

Thank you very much for your feedback, just let me know if you have any more questions / issues?

![Screenshot from 2021-03-17 17-41-56](https://user-images.githubusercontent.com/1760489/111542520-3a461a80-8748-11eb-9911-905179119732.png)

**Comment by Greensize** [comment]
Hi!
Make a nez install, here what I get…

**Comment by taoteh1221** [comment]
Hello! :) Did you attach a screenshot image? I don't see anything included with your message here. Try visiting the issue page on github.com ( https://github.com/taoteh1221/Slideshow_Crypto_Ticker/issues/9 ), and drag / drop any image file into the comments box.

**Comment by Greensize** [comment]
<img width="945" alt="Capture d’écran 2021-03-18 à 15 52 48" src="https://user-images.githubusercontent.com/80355995/111658063-4eebe680-880c-11eb-9d38-14711e66ecea.png">

**Comment by taoteh1221** [comment]
Hit the F5 button on your keyboard to reload the web page, your chrome temporary files for the pre-init.js file need to be refreshed to the new upgrade version. Looks like it's running the v3.02.0 version of that file.

**Comment by Greensize** [comment]
OMG...it doesn't work with F5

I do not know what to do...

**Comment by taoteh1221** [comment]
Okay, try this:

1) Close the chromium web browser

2) Go to your desktop menu, find the program 'Terminal', and open it...then type in this command, and hit the 'enter' key:

`rm -rf ~/.cache/chromium`

3) Now open chromium again, and view the ticker.

**Comment by taoteh1221** [comment]
That will delete your temporary files in chromuim, so the ticker should work fine after you do that.

**Comment by Greensize** [comment]
i reinstalled raspbian, everything is ok now. thank you

**Comment by taoteh1221** [comment]
Your welcome. Did you get kucoin to work? If not, open the error screen again, and follow the directions. Unfortunately you'll have to figure out running commands in the 'terminal' app on raspberry pi, if you want kucoin to work. 

Good, luck, and thanks for the feedback, it helps me make the app better  for everyone.

**Comment by Greensize** [comment]
kucoin work, but i have a bug with the $ ;)

<img width="1113" alt="Capture d’écran 2021-03-18 à 19 15 42" src="https://user-images.githubusercontent.com/80355995/111676503-85326180-881e-11eb-9468-0ec4a1158ea9.png">

**Comment by Greensize** [comment]
only with kucoin

**Comment by Greensize** [comment]
owww it's the symbol for theter! Sorry ;)

**Comment by taoteh1221** [comment]
I was wondering if that was you, thank you very much for the donation! :) 

That's the symbol for Tether, because it's a tether market that you added (notice the USDT, not USD). You can change the symbols to whatever you want them to be here in the config: https://github.com/taoteh1221/Slideshow_Crypto_Ticker/blob/main/config.js#L113

**Comment by taoteh1221** [comment]
I'm glad you figured out how to activate kucoin, mission accomplished! :)
